In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel("hepatitis_new.xlsx", header=None)
data

0    1    2        3           4        5        6         7   \
0    NaN    1    2        3           4        5        6         7   
1      #  Age  Sex  Steroid  Antivirals  Fatique  Malaise  Anorexia   
2      1   30  yes       no         yes      yes      yes       yes   
3      2   50   no       no         yes       no      yes       yes   
4      3   78   no      yes         yes       no      yes       yes   
..   ...  ...  ...      ...         ...      ...      ...       ...   
152  151   46   no      yes         yes       no       no        no   
153  152   44   no      yes         yes       no      yes       yes   
154  153   61   no       no         yes       no       no       yes   
155  154   53  yes       no         yes       no      yes       yes   
156  155   43   no      yes         yes       no      yes       yes   

            8           9   ...        11       12       13         14  \
0            8           9  ...        11       12       13         14   
1    Liver Big  Liver Firm  ...  Speiders  Ascites  Varices  Bilirubin   
2           no         yes  ...       yes      yes      yes          1   
3           no         yes  ...       yes      yes      yes        0.9   
4          yes         yes  ...       yes      yes      yes        0.7   
..         ...         ...  ...       ...      ...      ...        ...   
152        yes         yes  ...        no       no       no        7.6   
153        yes          no  ...       yes      yes      yes        0.9   
154         no          no  ...        no      yes      yes        0.8   
155        yes         yes  ...        no      yes       no        1.5   
156        yes         yes  ...        no       no      yes        1.2   

                15    16       17       18         19     20  
0               15    16       17       18         19    NaN  
1    Alk Phosphate  SGOT  Albumin  Protime  Histology  CLASS  
2               85    18        4        ?         no   Live  
3              135    42      3.5        ?         no   Live  
4               96    32        4        ?         no   Live  
..             ...   ...      ...      ...        ...    ...  
152              ?   242      3.3       50        yes    Die  
153            126   142      4.3        ?        yes   Live  
154             75    20      4.1        ?        yes   Live  
155             81    19      4.1       48        yes   Live  
156            100    19      3.1       42        yes    Die  

[157 rows x 21 columns]

In [3]:
data.drop(0, inplace=True, axis=1)
data

1    2        3           4        5        6         7          8   \
0      1    2        3           4        5        6         7          8   
1    Age  Sex  Steroid  Antivirals  Fatique  Malaise  Anorexia  Liver Big   
2     30  yes       no         yes      yes      yes       yes         no   
3     50   no       no         yes       no      yes       yes         no   
4     78   no      yes         yes       no      yes       yes        yes   
..   ...  ...      ...         ...      ...      ...       ...        ...   
152   46   no      yes         yes       no       no        no        yes   
153   44   no      yes         yes       no      yes       yes        yes   
154   61   no       no         yes       no       no       yes         no   
155   53  yes       no         yes       no      yes       yes        yes   
156   43   no      yes         yes       no      yes       yes        yes   

             9                10        11       12       13         14  \
0             9               10        11       12       13         14   
1    Liver Firm  Spleen Palpable  Speiders  Ascites  Varices  Bilirubin   
2           yes              yes       yes      yes      yes          1   
3           yes              yes       yes      yes      yes        0.9   
4           yes              yes       yes      yes      yes        0.7   
..          ...              ...       ...      ...      ...        ...   
152         yes              yes        no       no       no        7.6   
153          no              yes       yes      yes      yes        0.9   
154          no              yes        no      yes      yes        0.8   
155         yes               no        no      yes       no        1.5   
156         yes               no        no       no      yes        1.2   

                15    16       17       18         19     20  
0               15    16       17       18         19    NaN  
1    Alk Phosphate  SGOT  Albumin  Protime  Histology  CLASS  
2               85    18        4        ?         no   Live  
3              135    42      3.5        ?         no   Live  
4               96    32        4        ?         no   Live  
..             ...   ...      ...      ...        ...    ...  
152              ?   242      3.3       50        yes    Die  
153            126   142      4.3        ?        yes   Live  
154             75    20      4.1        ?        yes   Live  
155             81    19      4.1       48        yes   Live  
156            100    19      3.1       42        yes    Die  

[157 rows x 20 columns]

In [4]:
data.drop(0, inplace=True, axis=0)
data

1    2        3           4        5        6         7          8   \
1    Age  Sex  Steroid  Antivirals  Fatique  Malaise  Anorexia  Liver Big   
2     30  yes       no         yes      yes      yes       yes         no   
3     50   no       no         yes       no      yes       yes         no   
4     78   no      yes         yes       no      yes       yes        yes   
5     31   no        ?          no      yes      yes       yes        yes   
..   ...  ...      ...         ...      ...      ...       ...        ...   
152   46   no      yes         yes       no       no        no        yes   
153   44   no      yes         yes       no      yes       yes        yes   
154   61   no       no         yes       no       no       yes         no   
155   53  yes       no         yes       no      yes       yes        yes   
156   43   no      yes         yes       no      yes       yes        yes   

             9                10        11       12       13         14  \
1    Liver Firm  Spleen Palpable  Speiders  Ascites  Varices  Bilirubin   
2           yes              yes       yes      yes      yes          1   
3           yes              yes       yes      yes      yes        0.9   
4           yes              yes       yes      yes      yes        0.7   
5           yes              yes       yes      yes      yes        0.7   
..          ...              ...       ...      ...      ...        ...   
152         yes              yes        no       no       no        7.6   
153          no              yes       yes      yes      yes        0.9   
154          no              yes        no      yes      yes        0.8   
155         yes               no        no      yes       no        1.5   
156         yes               no        no       no      yes        1.2   

                15    16       17       18         19     20  
1    Alk Phosphate  SGOT  Albumin  Protime  Histology  CLASS  
2               85    18        4        ?         no   Live  
3              135    42      3.5        ?         no   Live  
4               96    32        4        ?         no   Live  
5               46    52        4       80         no   Live  
..             ...   ...      ...      ...        ...    ...  
152              ?   242      3.3       50        yes    Die  
153            126   142      4.3        ?        yes   Live  
154             75    20      4.1        ?        yes   Live  
155             81    19      4.1       48        yes   Live  
156            100    19      3.1       42        yes    Die  

[156 rows x 20 columns]

In [5]:
data.columns = data.iloc[0]
data.columns

Index(['Age', 'Sex', 'Steroid', 'Antivirals', 'Fatique', 'Malaise', 'Anorexia',
       'Liver Big', 'Liver Firm', 'Spleen Palpable', 'Speiders', 'Ascites',
       'Varices', 'Bilirubin', 'Alk Phosphate', 'SGOT', 'Albumin', 'Protime',
       'Histology', 'CLASS'],
      dtype='object', name=1)

In [6]:
data.drop(1, inplace=True, axis=0)
data

1   Age  Sex Steroid Antivirals Fatique Malaise Anorexia Liver Big Liver Firm  \
2    30  yes      no        yes     yes     yes      yes        no        yes   
3    50   no      no        yes      no     yes      yes        no        yes   
4    78   no     yes        yes      no     yes      yes       yes        yes   
5    31   no       ?         no     yes     yes      yes       yes        yes   
6    34   no     yes        yes     yes     yes      yes       yes        yes   
..   ..  ...     ...        ...     ...     ...      ...       ...        ...   
152  46   no     yes        yes      no      no       no       yes        yes   
153  44   no     yes        yes      no     yes      yes       yes         no   
154  61   no      no        yes      no      no      yes        no         no   
155  53  yes      no        yes      no     yes      yes       yes        yes   
156  43   no     yes        yes      no     yes      yes       yes        yes   

1   Spleen Palpable Speiders Ascites Varices Bilirubin Alk Phosphate SGOT  \
2               yes      yes     yes     yes         1            85   18   
3               yes      yes     yes     yes       0.9           135   42   
4               yes      yes     yes     yes       0.7            96   32   
5               yes      yes     yes     yes       0.7            46   52   
6               yes      yes     yes     yes         1             ?  200   
..              ...      ...     ...     ...       ...           ...  ...   
152             yes       no      no      no       7.6             ?  242   
153             yes      yes     yes     yes       0.9           126  142   
154             yes       no     yes     yes       0.8            75   20   
155              no       no     yes      no       1.5            81   19   
156              no       no      no     yes       1.2           100   19   

1   Albumin Protime Histology CLASS  
2         4       ?        no  Live  
3       3.5       ?        no  Live  
4         4       ?        no  Live  
5         4      80        no  Live  
6         4       ?        no  Live  
..      ...     ...       ...   ...  
152     3.3      50       yes   Die  
153     4.3       ?       yes  Live  
154     4.1       ?       yes  Live  
155     4.1      48       yes  Live  
156     3.1      42       yes   Die  

[155 rows x 20 columns]

In [7]:
data.columns = [c.replace(' ', '_') for c in data.columns]
data.columns

Index(['Age', 'Sex', 'Steroid', 'Antivirals', 'Fatique', 'Malaise', 'Anorexia',
       'Liver_Big', 'Liver_Firm', 'Spleen_Palpable', 'Speiders', 'Ascites',
       'Varices', 'Bilirubin', 'Alk_Phosphate', 'SGOT', 'Albumin', 'Protime',
       'Histology', 'CLASS'],
      dtype='object')

In [8]:
data = data.replace(to_replace=['no', 'yes'], value=[0, 1])
data

Age  Sex Steroid  Antivirals Fatique Malaise Anorexia Liver_Big  \
2     30    1       0           1       1       1        1         0   
3     50    0       0           1       0       1        1         0   
4     78    0       1           1       0       1        1         1   
5     31    0       ?           0       1       1        1         1   
6     34    0       1           1       1       1        1         1   
..   ...  ...     ...         ...     ...     ...      ...       ...   
152   46    0       1           1       0       0        0         1   
153   44    0       1           1       0       1        1         1   
154   61    0       0           1       0       0        1         0   
155   53    1       0           1       0       1        1         1   
156   43    0       1           1       0       1        1         1   

    Liver_Firm Spleen_Palpable Speiders Ascites Varices Bilirubin  \
2            1               1        1       1       1         1   
3            1               1        1       1       1       0.9   
4            1               1        1       1       1       0.7   
5            1               1        1       1       1       0.7   
6            1               1        1       1       1         1   
..         ...             ...      ...     ...     ...       ...   
152          1               1        0       0       0       7.6   
153          0               1        1       1       1       0.9   
154          0               1        0       1       1       0.8   
155          1               0        0       1       0       1.5   
156          1               0        0       0       1       1.2   

    Alk_Phosphate SGOT Albumin Protime  Histology CLASS  
2              85   18       4       ?          0  Live  
3             135   42     3.5       ?          0  Live  
4              96   32       4       ?          0  Live  
5              46   52       4      80          0  Live  
6               ?  200       4       ?          0  Live  
..            ...  ...     ...     ...        ...   ...  
152             ?  242     3.3      50          1   Die  
153           126  142     4.3       ?          1  Live  
154            75   20     4.1       ?          1  Live  
155            81   19     4.1      48          1  Live  
156           100   19     3.1      42          1   Die  

[155 rows x 20 columns]

In [9]:
data.CLASS = data.CLASS.replace(to_replace=['Live', 'Die'], value=[0, 1])
data.CLASS

2      0
3      0
4      0
5      0
6      0
      ..
152    1
153    0
154    0
155    0
156    1
Name: CLASS, Length: 155, dtype: int64

In [10]:
data = data.replace(to_replace=['?'], value=np.nan)
data

Age  Sex  Steroid  Antivirals  Fatique  Malaise  Anorexia  Liver_Big  \
2     30    1      0.0           1      1.0      1.0       1.0        0.0   
3     50    0      0.0           1      0.0      1.0       1.0        0.0   
4     78    0      1.0           1      0.0      1.0       1.0        1.0   
5     31    0      NaN           0      1.0      1.0       1.0        1.0   
6     34    0      1.0           1      1.0      1.0       1.0        1.0   
..   ...  ...      ...         ...      ...      ...       ...        ...   
152   46    0      1.0           1      0.0      0.0       0.0        1.0   
153   44    0      1.0           1      0.0      1.0       1.0        1.0   
154   61    0      0.0           1      0.0      0.0       1.0        0.0   
155   53    1      0.0           1      0.0      1.0       1.0        1.0   
156   43    0      1.0           1      0.0      1.0       1.0        1.0   

     Liver_Firm  Spleen_Palpable  Speiders  Ascites  Varices  Bilirubin  \
2           1.0              1.0       1.0      1.0      1.0        1.0   
3           1.0              1.0       1.0      1.0      1.0        0.9   
4           1.0              1.0       1.0      1.0      1.0        0.7   
5           1.0              1.0       1.0      1.0      1.0        0.7   
6           1.0              1.0       1.0      1.0      1.0        1.0   
..          ...              ...       ...      ...      ...        ...   
152         1.0              1.0       0.0      0.0      0.0        7.6   
153         0.0              1.0       1.0      1.0      1.0        0.9   
154         0.0              1.0       0.0      1.0      1.0        0.8   
155         1.0              0.0       0.0      1.0      0.0        1.5   
156         1.0              0.0       0.0      0.0      1.0        1.2   

     Alk_Phosphate   SGOT  Albumin  Protime  Histology  CLASS  
2             85.0   18.0      4.0      NaN          0      0  
3            135.0   42.0      3.5      NaN          0      0  
4             96.0   32.0      4.0      NaN          0      0  
5             46.0   52.0      4.0     80.0          0      0  
6              NaN  200.0      4.0      NaN          0      0  
..             ...    ...      ...      ...        ...    ...  
152            NaN  242.0      3.3     50.0          1      1  
153          126.0  142.0      4.3      NaN          1      0  
154           75.0   20.0      4.1      NaN          1      0  
155           81.0   19.0      4.1     48.0          1      0  
156          100.0   19.0      3.1     42.0          1      1  

[155 rows x 20 columns]

In [11]:
data = data.reset_index()
data

index  Age  Sex  Steroid  Antivirals  Fatique  Malaise  Anorexia  \
0        2   30    1      0.0           1      1.0      1.0       1.0   
1        3   50    0      0.0           1      0.0      1.0       1.0   
2        4   78    0      1.0           1      0.0      1.0       1.0   
3        5   31    0      NaN           0      1.0      1.0       1.0   
4        6   34    0      1.0           1      1.0      1.0       1.0   
..     ...  ...  ...      ...         ...      ...      ...       ...   
150    152   46    0      1.0           1      0.0      0.0       0.0   
151    153   44    0      1.0           1      0.0      1.0       1.0   
152    154   61    0      0.0           1      0.0      0.0       1.0   
153    155   53    1      0.0           1      0.0      1.0       1.0   
154    156   43    0      1.0           1      0.0      1.0       1.0   

     Liver_Big  Liver_Firm  ...  Speiders  Ascites  Varices  Bilirubin  \
0          0.0         1.0  ...       1.0      1.0      1.0        1.0   
1          0.0         1.0  ...       1.0      1.0      1.0        0.9   
2          1.0         1.0  ...       1.0      1.0      1.0        0.7   
3          1.0         1.0  ...       1.0      1.0      1.0        0.7   
4          1.0         1.0  ...       1.0      1.0      1.0        1.0   
..         ...         ...  ...       ...      ...      ...        ...   
150        1.0         1.0  ...       0.0      0.0      0.0        7.6   
151        1.0         0.0  ...       1.0      1.0      1.0        0.9   
152        0.0         0.0  ...       0.0      1.0      1.0        0.8   
153        1.0         1.0  ...       0.0      1.0      0.0        1.5   
154        1.0         1.0  ...       0.0      0.0      1.0        1.2   

     Alk_Phosphate   SGOT  Albumin  Protime  Histology  CLASS  
0             85.0   18.0      4.0      NaN          0      0  
1            135.0   42.0      3.5      NaN          0      0  
2             96.0   32.0      4.0      NaN          0      0  
3             46.0   52.0      4.0     80.0          0      0  
4              NaN  200.0      4.0      NaN          0      0  
..             ...    ...      ...      ...        ...    ...  
150            NaN  242.0      3.3     50.0          1      1  
151          126.0  142.0      4.3      NaN          1      0  
152           75.0   20.0      4.1      NaN          1      0  
153           81.0   19.0      4.1     48.0          1      0  
154          100.0   19.0      3.1     42.0          1      1  

[155 rows x 21 columns]

In [12]:
X_temp = data.drop(columns=['CLASS']).values
X_temp

array([[  2. ,  30. ,   1. , ...,   4. ,   nan,   0. ],
       [  3. ,  50. ,   0. , ...,   3.5,   nan,   0. ],
       [  4. ,  78. ,   0. , ...,   4. ,   nan,   0. ],
       ...,
       [154. ,  61. ,   0. , ...,   4.1,   nan,   1. ],
       [155. ,  53. ,   1. , ...,   4.1,  48. ,   1. ],
       [156. ,  43. ,   0. , ...,   3.1,  42. ,   1. ]])

In [13]:
y = data['CLASS'].values
y

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1], dtype=int64)

In [14]:
#Fill NaN with the mean values of same attribute in the same class
X = data.groupby("CLASS").transform(lambda x: x.fillna(x.mean()))
X.head

<bound method NDFrame.head of      index  Age  Sex   Steroid  Antivirals  Fatique  Malaise  Anorexia  \
0        2   30    1  0.000000           1      1.0      1.0       1.0   
1        3   50    0  0.000000           1      0.0      1.0       1.0   
2        4   78    0  1.000000           1      0.0      1.0       1.0   
3        5   31    0  0.540984           0      1.0      1.0       1.0   
4        6   34    0  1.000000           1      1.0      1.0       1.0   
..     ...  ...  ...       ...         ...      ...      ...       ...   
150    152   46    0  1.000000           1      0.0      0.0       0.0   
151    153   44    0  1.000000           1      0.0      1.0       1.0   
152    154   61    0  0.000000           1      0.0      0.0       1.0   
153    155   53    1  0.000000           1      0.0      1.0       1.0   
154    156   43    0  1.000000           1      0.0      1.0       1.0   

     Liver_Big  Liver_Firm  Spleen_Palpable  Speiders  Ascites  Varices  \
0     

In [15]:
column = X.columns
column

Index(['index', 'Age', 'Sex', 'Steroid', 'Antivirals', 'Fatique', 'Malaise',
       'Anorexia', 'Liver_Big', 'Liver_Firm', 'Spleen_Palpable', 'Speiders',
       'Ascites', 'Varices', 'Bilirubin', 'Alk_Phosphate', 'SGOT', 'Albumin',
       'Protime', 'Histology'],
      dtype='object')

In [16]:
# Hide the class label of the supervised data and do normalization
X = data.groupby("CLASS"). transform(lambda x: x.fillna(x.mean()))
X

index  Age  Sex   Steroid  Antivirals  Fatique  Malaise  Anorexia  \
0        2   30    1  0.000000           1      1.0      1.0       1.0   
1        3   50    0  0.000000           1      0.0      1.0       1.0   
2        4   78    0  1.000000           1      0.0      1.0       1.0   
3        5   31    0  0.540984           0      1.0      1.0       1.0   
4        6   34    0  1.000000           1      1.0      1.0       1.0   
..     ...  ...  ...       ...         ...      ...      ...       ...   
150    152   46    0  1.000000           1      0.0      0.0       0.0   
151    153   44    0  1.000000           1      0.0      1.0       1.0   
152    154   61    0  0.000000           1      0.0      0.0       1.0   
153    155   53    1  0.000000           1      0.0      1.0       1.0   
154    156   43    0  1.000000           1      0.0      1.0       1.0   

     Liver_Big  Liver_Firm  Spleen_Palpable  Speiders  Ascites  Varices  \
0          0.0         1.0              1.0       1.0      1.0      1.0   
1          0.0         1.0              1.0       1.0      1.0      1.0   
2          1.0         1.0              1.0       1.0      1.0      1.0   
3          1.0         1.0              1.0       1.0      1.0      1.0   
4          1.0         1.0              1.0       1.0      1.0      1.0   
..         ...         ...              ...       ...      ...      ...   
150        1.0         1.0              1.0       0.0      0.0      0.0   
151        1.0         0.0              1.0       1.0      1.0      1.0   
152        0.0         0.0              1.0       0.0      1.0      1.0   
153        1.0         1.0              0.0       0.0      1.0      0.0   
154        1.0         1.0              0.0       0.0      0.0      1.0   

     Bilirubin  Alk_Phosphate   SGOT  Albumin    Protime  Histology  
0          1.0      85.000000   18.0      4.0  66.571429          0  
1          0.9     135.000000   42.0      3.5  66.571429          0  
2          0.7      96.000000   32.0      4.0  66.571429          0  
3          0.7      46.000000   52.0      4.0  80.000000          0  
4          1.0     101.313725  200.0      4.0  66.571429          0  
..         ...            ...    ...      ...        ...        ...  
150        7.6     122.375000  242.0      3.3  50.000000          1  
151        0.9     126.000000  142.0      4.3  66.571429          1  
152        0.8      75.000000   20.0      4.1  66.571429          1  
153        1.5      81.000000   19.0      4.1  48.000000          1  
154        1.2     100.000000   19.0      3.1  42.000000          1  

[155 rows x 20 columns]

In [17]:
y = data["CLASS"].values
y

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1], dtype=int64)

In [18]:
X = X.values
X

array([[  2.        ,  30.        ,   1.        , ...,   4.        ,
         66.57142857,   0.        ],
       [  3.        ,  50.        ,   0.        , ...,   3.5       ,
         66.57142857,   0.        ],
       [  4.        ,  78.        ,   0.        , ...,   4.        ,
         66.57142857,   0.        ],
       ...,
       [154.        ,  61.        ,   0.        , ...,   4.1       ,
         66.57142857,   1.        ],
       [155.        ,  53.        ,   1.        , ...,   4.1       ,
         48.        ,   1.        ],
       [156.        ,  43.        ,   0.        , ...,   3.1       ,
         42.        ,   1.        ]])

In [19]:
from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()
#scaler.fit(X)
#X = scaler.transform(X)
X

array([[  2.        ,  30.        ,   1.        , ...,   4.        ,
         66.57142857,   0.        ],
       [  3.        ,  50.        ,   0.        , ...,   3.5       ,
         66.57142857,   0.        ],
       [  4.        ,  78.        ,   0.        , ...,   4.        ,
         66.57142857,   0.        ],
       ...,
       [154.        ,  61.        ,   0.        , ...,   4.1       ,
         66.57142857,   1.        ],
       [155.        ,  53.        ,   1.        , ...,   4.1       ,
         48.        ,   1.        ],
       [156.        ,  43.        ,   0.        , ...,   3.1       ,
         42.        ,   1.        ]])

In [20]:
# Cluster the data using K-Means or Hierarchical Clustering into 2 groups
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
kmeans.labels_

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1])

In [21]:
y

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1], dtype=int64)

In [22]:
# Do cluster analysis

# Accuracy
from sklearn.metrics import accuracy_score
acc = accuracy_score(y, kmeans.labels_)
acc

0.2645161290322581

In [23]:
error = (1-acc)*100
error

73.54838709677419

# FINALLLLL

In [24]:
import pandas as pd
import numpy as np

# 1. Convert that data into the numerical values

In [25]:
data = pd.read_excel("hepatitis_new.xlsx", header=None)
data.drop(0, inplace=True, axis=1)
data.drop(0, inplace=True, axis=0)
data.columns = data.iloc[0]
data.drop(1, inplace=True, axis=0)
data.columns = [c.replace(' ', '_') for c in data.columns]
data = data.replace(to_replace=['no', 'yes'], value=[0, 1])
data.CLASS = data.CLASS.replace(to_replace=['Live', 'Die'], value=[0, 1])
data = data.replace(to_replace=['?'], value=np.nan)
data = data.reset_index()
X_temp = data.drop(columns=['CLASS']).values
X_temp

array([[  2. ,  30. ,   1. , ...,   4. ,   nan,   0. ],
       [  3. ,  50. ,   0. , ...,   3.5,   nan,   0. ],
       [  4. ,  78. ,   0. , ...,   4. ,   nan,   0. ],
       ...,
       [154. ,  61. ,   0. , ...,   4.1,   nan,   1. ],
       [155. ,  53. ,   1. , ...,   4.1,  48. ,   1. ],
       [156. ,  43. ,   0. , ...,   3.1,  42. ,   1. ]])

In [26]:
y = data['CLASS'].values
y

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1], dtype=int64)

# 2. Impute the missing data with the mean values of same attribute in the same class

In [27]:
X = data.groupby("CLASS").transform(lambda x: x.fillna(x.mean()))
X

index  Age  Sex   Steroid  Antivirals  Fatique  Malaise  Anorexia  \
0        2   30    1  0.000000           1      1.0      1.0       1.0   
1        3   50    0  0.000000           1      0.0      1.0       1.0   
2        4   78    0  1.000000           1      0.0      1.0       1.0   
3        5   31    0  0.540984           0      1.0      1.0       1.0   
4        6   34    0  1.000000           1      1.0      1.0       1.0   
..     ...  ...  ...       ...         ...      ...      ...       ...   
150    152   46    0  1.000000           1      0.0      0.0       0.0   
151    153   44    0  1.000000           1      0.0      1.0       1.0   
152    154   61    0  0.000000           1      0.0      0.0       1.0   
153    155   53    1  0.000000           1      0.0      1.0       1.0   
154    156   43    0  1.000000           1      0.0      1.0       1.0   

     Liver_Big  Liver_Firm  Spleen_Palpable  Speiders  Ascites  Varices  \
0          0.0         1.0              1.0       1.0      1.0      1.0   
1          0.0         1.0              1.0       1.0      1.0      1.0   
2          1.0         1.0              1.0       1.0      1.0      1.0   
3          1.0         1.0              1.0       1.0      1.0      1.0   
4          1.0         1.0              1.0       1.0      1.0      1.0   
..         ...         ...              ...       ...      ...      ...   
150        1.0         1.0              1.0       0.0      0.0      0.0   
151        1.0         0.0              1.0       1.0      1.0      1.0   
152        0.0         0.0              1.0       0.0      1.0      1.0   
153        1.0         1.0              0.0       0.0      1.0      0.0   
154        1.0         1.0              0.0       0.0      0.0      1.0   

     Bilirubin  Alk_Phosphate   SGOT  Albumin    Protime  Histology  
0          1.0      85.000000   18.0      4.0  66.571429          0  
1          0.9     135.000000   42.0      3.5  66.571429          0  
2          0.7      96.000000   32.0      4.0  66.571429          0  
3          0.7      46.000000   52.0      4.0  80.000000          0  
4          1.0     101.313725  200.0      4.0  66.571429          0  
..         ...            ...    ...      ...        ...        ...  
150        7.6     122.375000  242.0      3.3  50.000000          1  
151        0.9     126.000000  142.0      4.3  66.571429          1  
152        0.8      75.000000   20.0      4.1  66.571429          1  
153        1.5      81.000000   19.0      4.1  48.000000          1  
154        1.2     100.000000   19.0      3.1  42.000000          1  

[155 rows x 20 columns]

In [28]:
column = X.columns
column

Index(['index', 'Age', 'Sex', 'Steroid', 'Antivirals', 'Fatique', 'Malaise',
       'Anorexia', 'Liver_Big', 'Liver_Firm', 'Spleen_Palpable', 'Speiders',
       'Ascites', 'Varices', 'Bilirubin', 'Alk_Phosphate', 'SGOT', 'Albumin',
       'Protime', 'Histology'],
      dtype='object')

# 3. Hide the class label of the supervised data

# 4. Cluster the data using K-Means or Hierarchical Clustering into 2 groups

In [29]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
kmeans.labels_

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1])

In [30]:
y

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1], dtype=int64)

# 5. Do cluster analysis

In [31]:
# Accuracy
from sklearn.metrics import accuracy_score
acc = accuracy_score(y, kmeans.labels_)
acc*100

26.451612903225808

In [32]:
error = (1-acc)*100
error

73.54838709677419