In [4]:
import pandas as pd
import numpy as np

data = pd.read_excel("hepatitis_new.xlsx", header=None)
data.drop(0, inplace=True, axis=1)
data.drop(0, inplace=True, axis=0)
data.columns = data.iloc[0]
data.drop(1, inplace=True, axis=0)
data.columns = [c.replace(' ', '_') for c in data.columns]
data = data.replace(to_replace=['no', 'yes'], value=[0, 1])
data.CLASS = data.CLASS.replace(to_replace=['Live', 'Die'], value=[0, 1])
data = data.replace(to_replace=['?'], value=np.nan)
data = data.reset_index()
X_temp = data.drop(columns=['CLASS'])
X_temp

index  Age  Sex  Steroid  Antivirals  Fatique  Malaise  Anorexia  \
0        2   30    1      0.0           1      1.0      1.0       1.0   
1        3   50    0      0.0           1      0.0      1.0       1.0   
2        4   78    0      1.0           1      0.0      1.0       1.0   
3        5   31    0      NaN           0      1.0      1.0       1.0   
4        6   34    0      1.0           1      1.0      1.0       1.0   
..     ...  ...  ...      ...         ...      ...      ...       ...   
150    152   46    0      1.0           1      0.0      0.0       0.0   
151    153   44    0      1.0           1      0.0      1.0       1.0   
152    154   61    0      0.0           1      0.0      0.0       1.0   
153    155   53    1      0.0           1      0.0      1.0       1.0   
154    156   43    0      1.0           1      0.0      1.0       1.0   

     Liver_Big  Liver_Firm  Spleen_Palpable  Speiders  Ascites  Varices  \
0          0.0         1.0              1.0       1.0      1.0      1.0   
1          0.0         1.0              1.0       1.0      1.0      1.0   
2          1.0         1.0              1.0       1.0      1.0      1.0   
3          1.0         1.0              1.0       1.0      1.0      1.0   
4          1.0         1.0              1.0       1.0      1.0      1.0   
..         ...         ...              ...       ...      ...      ...   
150        1.0         1.0              1.0       0.0      0.0      0.0   
151        1.0         0.0              1.0       1.0      1.0      1.0   
152        0.0         0.0              1.0       0.0      1.0      1.0   
153        1.0         1.0              0.0       0.0      1.0      0.0   
154        1.0         1.0              0.0       0.0      0.0      1.0   

     Bilirubin  Alk_Phosphate   SGOT  Albumin  Protime  Histology  
0          1.0           85.0   18.0      4.0      NaN          0  
1          0.9          135.0   42.0      3.5      NaN          0  
2          0.7           96.0   32.0      4.0      NaN          0  
3          0.7           46.0   52.0      4.0     80.0          0  
4          1.0            NaN  200.0      4.0      NaN          0  
..         ...            ...    ...      ...      ...        ...  
150        7.6            NaN  242.0      3.3     50.0          1  
151        0.9          126.0  142.0      4.3      NaN          1  
152        0.8           75.0   20.0      4.1      NaN          1  
153        1.5           81.0   19.0      4.1     48.0          1  
154        1.2          100.0   19.0      3.1     42.0          1  

[155 rows x 20 columns]

In [5]:
X = data.groupby("CLASS").transform(lambda x: x.fillna(x.mean()))
X

index  Age  Sex   Steroid  Antivirals  Fatique  Malaise  Anorexia  \
0        2   30    1  0.000000           1      1.0      1.0       1.0   
1        3   50    0  0.000000           1      0.0      1.0       1.0   
2        4   78    0  1.000000           1      0.0      1.0       1.0   
3        5   31    0  0.540984           0      1.0      1.0       1.0   
4        6   34    0  1.000000           1      1.0      1.0       1.0   
..     ...  ...  ...       ...         ...      ...      ...       ...   
150    152   46    0  1.000000           1      0.0      0.0       0.0   
151    153   44    0  1.000000           1      0.0      1.0       1.0   
152    154   61    0  0.000000           1      0.0      0.0       1.0   
153    155   53    1  0.000000           1      0.0      1.0       1.0   
154    156   43    0  1.000000           1      0.0      1.0       1.0   

     Liver_Big  Liver_Firm  Spleen_Palpable  Speiders  Ascites  Varices  \
0          0.0         1.0              1.0       1.0      1.0      1.0   
1          0.0         1.0              1.0       1.0      1.0      1.0   
2          1.0         1.0              1.0       1.0      1.0      1.0   
3          1.0         1.0              1.0       1.0      1.0      1.0   
4          1.0         1.0              1.0       1.0      1.0      1.0   
..         ...         ...              ...       ...      ...      ...   
150        1.0         1.0              1.0       0.0      0.0      0.0   
151        1.0         0.0              1.0       1.0      1.0      1.0   
152        0.0         0.0              1.0       0.0      1.0      1.0   
153        1.0         1.0              0.0       0.0      1.0      0.0   
154        1.0         1.0              0.0       0.0      0.0      1.0   

     Bilirubin  Alk_Phosphate   SGOT  Albumin    Protime  Histology  
0          1.0      85.000000   18.0      4.0  66.571429          0  
1          0.9     135.000000   42.0      3.5  66.571429          0  
2          0.7      96.000000   32.0      4.0  66.571429          0  
3          0.7      46.000000   52.0      4.0  80.000000          0  
4          1.0     101.313725  200.0      4.0  66.571429          0  
..         ...            ...    ...      ...        ...        ...  
150        7.6     122.375000  242.0      3.3  50.000000          1  
151        0.9     126.000000  142.0      4.3  66.571429          1  
152        0.8      75.000000   20.0      4.1  66.571429          1  
153        1.5      81.000000   19.0      4.1  48.000000          1  
154        1.2     100.000000   19.0      3.1  42.000000          1  

[155 rows x 20 columns]

In [6]:
y = data['CLASS'].values
y

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1], dtype=int64)

In [13]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X)

X_scaled2 = scaler.transform(X)
X_scaled2

array([[-1.7209121 , -0.89419175,  2.94745653, ...,  0.30720513,
         0.26151157, -0.90748521],
       [-1.69856259,  0.70257923, -0.33927557, ..., -0.48942799,
         0.26151157, -0.90748521],
       [-1.67621309,  2.93805862, -0.33927557, ...,  0.30720513,
         0.26151157, -0.90748521],
       ...,
       [ 1.67621309,  1.58080328, -0.33927557, ...,  0.46653176,
         0.26151157,  1.10194633],
       [ 1.69856259,  0.94209488,  2.94745653, ...,  0.46653176,
        -0.75812043,  1.10194633],
       [ 1.7209121 ,  0.14370939, -0.33927557, ..., -1.1267345 ,
        -1.08753999,  1.10194633]])

In [14]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2, random_state=0).fit(X_scaled2)
kmeans.labels_

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1])

In [15]:
# Accuracy
from sklearn.metrics import accuracy_score
acc = accuracy_score(y, kmeans.labels_)
acc*100

79.35483870967742

In [16]:
kmeans_random = KMeans(init="random", n_clusters=2, random_state=0).fit(X_scaled2)
kmeans_random.labels_

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0])

In [18]:
kmeans_random.cluster_centers_

array([[ 0.56552237,  0.31479199,  0.18894923, -0.19263914,  0.32929963,
        -0.70065335, -0.69035515, -0.41388661, -0.14954678, -0.37227622,
        -0.46885734, -0.87598794, -0.69376657, -0.59622795,  0.66649659,
         0.59670785,  0.38080135, -0.80408547, -0.63486821,  0.63547115],
       [-0.31989144, -0.17806416, -0.10688037,  0.1089676 , -0.1862705 ,
         0.39632917,  0.39050393,  0.23411768,  0.08459212,  0.21058049,
         0.26521223,  0.49550833,  0.39243361,  0.33726025, -0.37700817,
        -0.33753172, -0.21540279,  0.45483623,  0.35911737, -0.35945843]])

In [17]:
# Accuracy
from sklearn.metrics import accuracy_score
acc = accuracy_score(y, kmeans_random.labels_)
acc*100

20.64516129032258